export const ENEMY_TABLE = [
    { key: 'old_hag', name: 'Old Hag', minLevel: 1, maxLevel: 3, hpBase: 14, hpPerLevel: 3, attackBase: 2, attackPerLevel: 1, defenseBase: 0, defensePerLevel: 0, goldBase: 8, goldPerLevel: 3, expBase: 6, expPerLevel: 3, gemChance: 0.04, dangerRating: 1 },
    { key: 'small_troll', name: 'Small Troll', minLevel: 1, maxLevel: 3, hpBase: 16, hpPerLevel: 3, attackBase: 3, attackPerLevel: 1, defenseBase: 1, defensePerLevel: 0, goldBase: 9, goldPerLevel: 3, expBase: 8, expPerLevel: 3, gemChance: 0.05, dangerRating: 2 },
    { key: 'raging_lion', name: 'Raging Lion', minLevel: 1, maxLevel: 3, hpBase: 15, hpPerLevel: 4, attackBase: 3, attackPerLevel: 1, defenseBase: 1, defensePerLevel: 0, goldBase: 10, goldPerLevel: 3, expBase: 9, expPerLevel: 3, gemChance: 0.06, dangerRating: 2 },
    { key: 'werewolf', name: 'Werewolf', minLevel: 4, maxLevel: 6, hpBase: 24, hpPerLevel: 4, attackBase: 5, attackPerLevel: 1, defenseBase: 2, defensePerLevel: 0, goldBase: 14, goldPerLevel: 4, expBase: 14, expPerLevel: 4, gemChance: 0.08, dangerRating: 3 },
    { key: 'bellar', name: 'Bellar', minLevel: 4, maxLevel: 6, hpBase: 26, hpPerLevel: 4, attackBase: 5, attackPerLevel: 2, defenseBase: 2, defensePerLevel: 0, goldBase: 15, goldPerLevel: 4, expBase: 15, expPerLevel: 4, gemChance: 0.09, dangerRating: 3 },
    { key: 'floating_evil_eye', name: 'Floating Evil Eye', minLevel: 4, maxLevel: 6, hpBase: 22, hpPerLevel: 4, attackBase: 6, attackPerLevel: 1, defenseBase: 2, defensePerLevel: 0, goldBase: 16, goldPerLevel: 4, expBase: 15, expPerLevel: 4, gemChance: 0.1, dangerRating: 3 },
    { key: 'earth_shaker', name: 'Earth Shaker', minLevel: 7, maxLevel: 9, hpBase: 34, hpPerLevel: 5, attackBase: 7, attackPerLevel: 2, defenseBase: 3, defensePerLevel: 1, goldBase: 24, goldPerLevel: 5, expBase: 22, expPerLevel: 5, gemChance: 0.12, dangerRating: 4 },
    { key: 'king_vidian', name: 'King Vidian', minLevel: 7, maxLevel: 9, hpBase: 36, hpPerLevel: 5, attackBase: 8, attackPerLevel: 2, defenseBase: 3, defensePerLevel: 1, goldBase: 25, goldPerLevel: 5, expBase: 24, expPerLevel: 5, gemChance: 0.13, dangerRating: 4 },
    { key: 'swiss_push_butcher', name: 'Swiss Push Butcher', minLevel: 7, maxLevel: 9, hpBase: 35, hpPerLevel: 6, attackBase: 8, attackPerLevel: 2, defenseBase: 3, defensePerLevel: 1, goldBase: 27, goldPerLevel: 5, expBase: 25, expPerLevel: 5, gemChance: 0.14, dangerRating: 4 },
    { key: 'wizard_of_darkness', name: 'Wizard of Darkness', minLevel: 10, maxLevel: 12, hpBase: 45, hpPerLevel: 6, attackBase: 10, attackPerLevel: 2, defenseBase: 4, defensePerLevel: 1, goldBase: 34, goldPerLevel: 6, expBase: 32, expPerLevel: 6, gemChance: 0.16, dangerRating: 5 },
    { key: 'screaming_unicorn', name: 'Screaming Unicorn', minLevel: 10, maxLevel: 12, hpBase: 46, hpPerLevel: 6, attackBase: 10, attackPerLevel: 2, defenseBase: 4, defensePerLevel: 1, goldBase: 36, goldPerLevel: 6, expBase: 34, expPerLevel: 6, gemChance: 0.18, dangerRating: 5 },
    { key: 'black_soul', name: 'Black Soul', minLevel: 10, maxLevel: 12, hpBase: 44, hpPerLevel: 7, attackBase: 11, attackPerLevel: 2, defenseBase: 5, defensePerLevel: 1, goldBase: 38, goldPerLevel: 6, expBase: 35, expPerLevel: 6, gemChance: 0.2, dangerRating: 5 }
];
