export const config = {
    timezone: process.env.LORD_TIMEZONE ?? 'America/New_York',
    forestTurnsBase: Number(process.env.LORD_FOREST_TURNS_BASE ?? '30'),
    forestTurnsMin: Number(process.env.LORD_FOREST_TURNS_MIN ?? '5'),
    forestFightsPerDay: Number(process.env.LORD_FOREST_FIGHTS_PER_DAY ?? '30'),
    pvpAttacksPerDay: Number(process.env.LORD_PVP_ATTACKS_PER_DAY ?? '1'),
    bardMaxListensPerDay: Number(process.env.LORD_BARD_MAX_LISTENS_PER_DAY ?? '1'),
    enableDailyNewsAutoShow: (process.env.LORD_ENABLE_DAILY_NEWS_AUTO_SHOW ?? 'true') === 'true',
    innElixirGoldCost: Number(process.env.LORD_INN_ELIXIR_GOLD_COST ?? '1000'),
    innGemTradeCost: Number(process.env.LORD_INN_GEM_TRADE_COST ?? '2'),
    innBribeCost: Number(process.env.LORD_INN_BRIBE_COST ?? '2000'),
    innRoomCost: Number(process.env.LORD_INN_ROOM_COST ?? '800'),
    innRoomCostPerLevel: Number(process.env.LORD_INN_ROOM_COST_PER_LEVEL ?? '200'),
    innBardBonusFights: Number(process.env.LORD_INN_BARD_BONUS_FIGHTS ?? '2'),
    sethMaxListensPerDay: Number(process.env.LORD_SETH_MAX_LISTENS_PER_DAY ?? process.env.LORD_BARD_MAX_LISTENS_PER_DAY ?? '1'),
    bankInterestRate: Number(process.env.LORD_BANK_INTEREST_RATE ?? process.env.LORD_BANK_DAILY_INTEREST_RATE ?? '0.10'),
    bankInterestCap: process.env.LORD_BANK_INTEREST_CAP ? Number(process.env.LORD_BANK_INTEREST_CAP) : null,
    moneyDoublerChance: Number(process.env.LORD_MONEY_DOUBLER_CHANCE ?? '0.02'),
    skillDailyUsesCap: Number(process.env.LORD_SKILL_DAILY_USES_CAP ?? '12'),
    skillMasteryLevel: Number(process.env.LORD_SKILL_MASTERY_LEVEL ?? '30'),
    healerCostPerHp: Number(process.env.LORD_HEAL_COST_PER_HP ?? '10'),
    healerMinPurchase: Number(process.env.LORD_HEALER_MIN_PURCHASE ?? '1'),
    healerAllowOverheal: (process.env.LORD_HEALER_ALLOW_OVERHEAL ?? 'false') === 'true',
    baseAtk: Number(process.env.LORD_BASE_ATK ?? '5'),
    baseDef: Number(process.env.LORD_BASE_DEF ?? '0'),
    dragonHp: Number(process.env.LORD_DRAGON_HP ?? '5000'),
    dragonAttackMin: Number(process.env.LORD_DRAGON_ATTACK_MIN ?? '40'),
    dragonAttackMax: Number(process.env.LORD_DRAGON_ATTACK_MAX ?? '120'),
    dragonMissChance: Number(process.env.LORD_DRAGON_MISS_CHANCE ?? '0.10'),
    playerMissChance: Number(process.env.LORD_PLAYER_MISS_CHANCE ?? '0.12'),
    dragonCritChance: Number(process.env.LORD_DRAGON_CRIT_CHANCE ?? '0.08'),
    dragonCritMult: Number(process.env.LORD_DRAGON_CRIT_MULT ?? '1.8'),
    dragonFairyReviveHpRatio: Number(process.env.LORD_DRAGON_FAIRY_REVIVE_HP_RATIO ?? '0.35'),
    dragonResetKeepBankGold: (process.env.LORD_DRAGON_RESET_KEEP_BANK_GOLD ?? 'true') === 'true',
    dragonResetKeepEquipment: (process.env.LORD_DRAGON_RESET_KEEP_EQUIPMENT ?? 'false') === 'true',
    dragonResetKeepElixirs: (process.env.LORD_DRAGON_RESET_KEEP_ELIXIRS ?? 'false') === 'true',
    dragonResetKeepCharm: (process.env.LORD_DRAGON_RESET_KEEP_CHARM ?? 'false') === 'true',
    dragonResetKeepSkillMastery: (process.env.LORD_DRAGON_RESET_KEEP_SKILL_MASTERY ?? 'true') === 'true',
    dragonResetGoldOnHand: Number(process.env.LORD_DRAGON_RESET_GOLD_ON_HAND ?? '0'),
    baseHp: Number(process.env.LORD_BASE_HP ?? '20'),
    roomExpiresDaily: (process.env.LORD_ROOM_EXPIRES_DAILY ?? 'true') === 'true',
    spiritsChances: {
        high: Number(process.env.LORD_SPIRITS_HIGH_CHANCE ?? '0.25'),
        low: Number(process.env.LORD_SPIRITS_LOW_CHANCE ?? '0.25')
    }
};
